# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, sourcelibscanner!
  displayName: 'Run a one-line test BEROE script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    sourceandlibscanner -auto -bt none -f my.fpr -scan
  displayName: 'Sourcelibscannertest'
